/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/*package com.gradle.demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class DemoApplicationTest {
    @Test public void testAppHasAGreeting() {
        DemoApplication classUnderTest = new DemoApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}*/
